-- ============================================================================
-- System Administrator Setup with Role-Based Access Control
-- ============================================================================
-- This script creates:
-- 1. A system administrator user account
-- 2. A dedicated role (ADMIN_PASSWORD_MANAGER) that can update admin password
-- 3. Grants this role ONLY to the videxakc user
-- 4. A secure stored procedure for password updates
-- ============================================================================

USE DATABASE NEXUS_DB;
USE SCHEMA PUBLIC;

-- ============================================================================
-- STEP 1: Create System Administrator User
-- ============================================================================
-- Admin Email: system.admin@videxa.com
-- Initial Password: 8a093b79-bee6-4d70-8a98-2bc7657c8e7f (GUID)
-- Account Type: system_admin
-- Email Verified: true (system account)
-- ============================================================================

INSERT INTO USER_PROFILES (
    USER_ID,
    EMAIL,
    PASSWORD_HASH,
    ORGANIZATION_NAME,
    ACCOUNT_TYPE,
    EMAIL_VERIFIED,
    REGISTRATION_METHOD,
    CREATED_AT,
    UPDATED_AT
)
SELECT
    'system-admin-00000000-0000-0000-0000-000000000001',
    'system.admin@videxa.com',
    -- Password hash for: 8a093b79-bee6-4d70-8a98-2bc7657c8e7f
    -- This must be generated by backend using bcrypt with 12 rounds
    '$2b$12$PLACEHOLDER_HASH_TO_BE_REPLACED',
    'Videxa System',
    'system_admin',
    TRUE,
    'system_initialization',
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
WHERE NOT EXISTS (
    SELECT 1 FROM USER_PROFILES WHERE EMAIL = 'system.admin@videxa.com'
);

-- ============================================================================
-- STEP 2: Create Dedicated Role for Admin Password Management
-- ============================================================================
-- Only users with this role can update the system admin password
-- ============================================================================

CREATE ROLE IF NOT EXISTS ADMIN_PASSWORD_MANAGER
    COMMENT = 'Role that can update system administrator password - assigned only to videxakc';

-- ============================================================================
-- STEP 3: Grant Role to videxakc User ONLY
-- ============================================================================
-- This ensures only the videxakc user can manage admin passwords
-- ============================================================================

GRANT ROLE ADMIN_PASSWORD_MANAGER TO USER videxakc;

-- ============================================================================
-- STEP 4: Create Secure Stored Procedure for Password Updates
-- ============================================================================
-- This procedure can only be executed by users with ADMIN_PASSWORD_MANAGER role
-- It validates the caller and updates the password hash securely
-- ============================================================================

CREATE OR REPLACE PROCEDURE UPDATE_SYSTEM_ADMIN_PASSWORD(
    NEW_PASSWORD_HASH VARCHAR(255)
)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN
    -- Update the system admin password
    UPDATE USER_PROFILES
    SET
        PASSWORD_HASH = NEW_PASSWORD_HASH,
        UPDATED_AT = CURRENT_TIMESTAMP()
    WHERE EMAIL = 'system.admin@videxa.com';

    -- Return success message
    RETURN 'System administrator password updated successfully';
END;
$$;

-- Grant EXECUTE permission on the procedure to ADMIN_PASSWORD_MANAGER role only
GRANT USAGE ON PROCEDURE UPDATE_SYSTEM_ADMIN_PASSWORD(VARCHAR) TO ROLE ADMIN_PASSWORD_MANAGER;

-- ============================================================================
-- STEP 5: Create View for Safe Admin Information Viewing
-- ============================================================================
-- This view shows admin info without exposing the password hash
-- ============================================================================

CREATE OR REPLACE VIEW SYSTEM_ADMIN_INFO AS
SELECT
    USER_ID,
    EMAIL,
    ORGANIZATION_NAME,
    ACCOUNT_TYPE,
    EMAIL_VERIFIED,
    REGISTRATION_METHOD,
    CREATED_AT,
    UPDATED_AT,
    '***REDACTED***' AS PASSWORD_HASH
FROM USER_PROFILES
WHERE ACCOUNT_TYPE = 'system_admin';

-- Grant SELECT on view to all authenticated users (they can see it exists)
GRANT SELECT ON VIEW SYSTEM_ADMIN_INFO TO ROLE PUBLIC;

-- ============================================================================
-- STEP 6: Create Audit Log for Password Changes
-- ============================================================================

CREATE TABLE IF NOT EXISTS ADMIN_PASSWORD_AUDIT (
    AUDIT_ID VARCHAR(36) DEFAULT UUID_STRING(),
    USER_EMAIL VARCHAR(255),
    CHANGED_BY_USER VARCHAR(255),
    CHANGED_BY_ROLE VARCHAR(255),
    CHANGE_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ACTION_TYPE VARCHAR(50),
    SUCCESS BOOLEAN,
    ERROR_MESSAGE VARCHAR(500)
);

-- Create audit trigger stored procedure
CREATE OR REPLACE PROCEDURE LOG_ADMIN_PASSWORD_CHANGE(
    USER_EMAIL VARCHAR,
    ACTION_TYPE VARCHAR,
    SUCCESS BOOLEAN,
    ERROR_MESSAGE VARCHAR
)
RETURNS VARCHAR
LANGUAGE SQL
AS
$$
BEGIN
    INSERT INTO ADMIN_PASSWORD_AUDIT (
        USER_EMAIL,
        CHANGED_BY_USER,
        CHANGED_BY_ROLE,
        ACTION_TYPE,
        SUCCESS,
        ERROR_MESSAGE
    )
    VALUES (
        USER_EMAIL,
        CURRENT_USER(),
        CURRENT_ROLE(),
        ACTION_TYPE,
        SUCCESS,
        ERROR_MESSAGE
    );

    RETURN 'Audit log entry created';
END;
$$;

-- Grant execute to ADMIN_PASSWORD_MANAGER
GRANT USAGE ON PROCEDURE LOG_ADMIN_PASSWORD_CHANGE(VARCHAR, VARCHAR, BOOLEAN, VARCHAR)
    TO ROLE ADMIN_PASSWORD_MANAGER;

-- ============================================================================
-- STEP 7: Verification Queries (for documentation purposes)
-- ============================================================================

-- Verify system admin was created:
-- SELECT * FROM SYSTEM_ADMIN_INFO;

-- Verify role assignment:
-- SHOW GRANTS TO USER videxakc;

-- Verify procedure exists:
-- SHOW PROCEDURES LIKE 'UPDATE_SYSTEM_ADMIN_PASSWORD';

-- View audit log:
-- SELECT * FROM ADMIN_PASSWORD_AUDIT ORDER BY CHANGE_TIMESTAMP DESC;

-- ============================================================================
-- USAGE INSTRUCTIONS
-- ============================================================================
--
-- To update system admin password (as videxakc user):
--
-- 1. Switch to ADMIN_PASSWORD_MANAGER role:
--    USE ROLE ADMIN_PASSWORD_MANAGER;
--
-- 2. Generate new password hash in backend (bcrypt, 12 rounds)
--
-- 3. Call the stored procedure:
--    CALL UPDATE_SYSTEM_ADMIN_PASSWORD('$2b$12$new_hash_here');
--
-- 4. Log the change:
--    CALL LOG_ADMIN_PASSWORD_CHANGE(
--        'system.admin@videxa.com',
--        'PASSWORD_RESET',
--        TRUE,
--        NULL
--    );
--
-- ============================================================================
